# Generated by Django 5.1.1 on 2024-09-05 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('main_genre', models.CharField(choices=[('ROMANCE', 'romance'), ('MiSTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy')], max_length=13)),
                ('mix_genre', models.CharField(choices=[('ROMANCE', 'romance'), ('MiSTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PLOT', 'Plot'), ('CHARACTER', 'Character'), ('THEME', 'Theme'), ('SETTING', 'Setting'), ('NONE', 'None')], default='NONE', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideasrecording.project')),
            ],
        ),
    ]
