# Generated by Django 5.1.1 on 2025-01-22 16:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_genre', models.CharField(blank=True, choices=[('ROMANCE', 'romance'), ('MISTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy'), ('NONE', 'none')], max_length=13)),
                ('mix_genre', models.CharField(blank=True, choices=[('ROMANCE', 'romance'), ('MISTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy'), ('NONE', 'none')], max_length=13)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, default='Untitled', max_length=100)),
                ('category', models.CharField(choices=[('PLOT', 'Plot'), ('CHARACTER', 'Character'), ('THEME', 'Theme'), ('SETTING', 'Setting'), ('RESEARCH', 'Research'), ('RANDOM', 'Random')], default='RANDOM', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideasrecording.project')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idea_search_idx')],
            },
        ),
    ]
