# Generated by Django 5.1.1 on 2024-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasrecording', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('PLOT', 'Plot'), ('CHARACTER', 'Character'), ('THEME', 'Theme'), ('SETTING', 'Setting'), ('RESEARCH', 'Research'), ('RANDOM', 'Random')], default='RANDOM', max_length=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_genre',
            field=models.CharField(choices=[('ROMANCE', 'romance'), ('MISTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy')], max_length=13),
        ),
        migrations.AlterField(
            model_name='project',
            name='mix_genre',
            field=models.CharField(choices=[('ROMANCE', 'romance'), ('MISTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy')], max_length=13),
        ),
    ]
