# Generated by Django 5.1.1 on 2024-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasrecording', '0003_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mix_genre',
            field=models.CharField(blank=True, choices=[('ROMANCE', 'romance'), ('MISTERY', 'mistery'), ('SCI-FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('DETECTIVE', 'detective'), ('HORROR', 'horror'), ('COMING OF AGE', 'coming of age'), ('COMEDY', 'comedy')], max_length=13),
        ),
    ]
