# Generated by Django 5.1.1 on 2024-10-22 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasrecording', '0005_alter_project_main_genre_alter_project_mix_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='id',
        ),
        migrations.AddField(
            model_name='idea',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
