# Generated by Django 5.1.1 on 2024-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasrecording', '0006_remove_idea_id_idea_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=100),
        ),
    ]
