# Generated by Django 5.1.1 on 2025-01-15 15:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideasrecording', '0008_alter_project_main_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idea_search_idx'),
        ),
    ]
