# Generated by Django 5.1.1 on 2025-01-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_first_name_useraccount_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='unique_id',
            new_name='id',
        ),
    ]
