# Generated by Django 5.1.1 on 2025-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_unique_id_useraccount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
            preserve_default=False,
        ),
    ]
